apiVersion: batch/v1
kind: Job
metadata:
  name: jx-boot
spec:
  template:
    spec:
      containers:
      - name: jx-boot
        image: busybox
        command: ["echo", "This is a minimal job for JX Git Operator"]
      restartPolicy: Never
